Repository ProjectSOEN341/Project_SOEN341, pull requests merged in 2025-02, with the labels that each got.

#16 Update README.md
  README.md
Labels: documentation

#17 Update README.md
  README.md
Labels: setup

#27 Task setting up websocket connection #20
  soen341-backend/pom.xml
  soen341-backend/src/main/java/soen341/backend/Config/WebSocketConfig.java
  soen341-backend/src/main/java/soen341/backend/Controller/GreetingController.java
  soen341-backend/src/main/java/soen341/backend/Controller/MainController.java
  soen341-backend/src/main/java/soen341/backend/Entity/Greeting.java
  soen341-backend/src/main/java/soen341/backend/Entity/HelloMessage.java
  soen341-backend/src/main/java/soen341/backend/Entity/User.java
  soen341-backend/src/main/java/soen341/backend/Repository/UserRepository.java
  soen341-backend/src/main/resources/static/app.js
  soen341-backend/src/main/resources/static/index.html
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
  soen341-frontend/src/app/app.component.html
  soen341-frontend/src/app/app.component.ts
  soen341-frontend/src/app/app.routes.ts
  soen341-frontend/src/app/direct-messages/direct-messages.component.css
  soen341-frontend/src/app/direct-messages/direct-messages.component.html
  soen341-frontend/src/app/direct-messages/direct-messages.component.spec.ts
  soen341-frontend/src/app/direct-messages/direct-messages.component.ts
Labels: Blocking Priority, High Risk

#30 US messaging UI #26
  soen341-backend/.idea/dataSources.local.xml
  soen341-backend/.idea/workspace.xml
  soen341-frontend/angular.json
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
  soen341-frontend/src/app/app.component.ts
  soen341-frontend/src/app/app.config.ts
  soen341-frontend/src/app/app.routes.ts
  soen341-frontend/src/app/home/home.component.css
  soen341-frontend/src/app/home/home.component.html
  soen341-frontend/src/app/home/home.component.spec.ts
  soen341-frontend/src/app/home/home.component.ts
  soen341-frontend/src/custom-theme.scss
  soen341-frontend/src/index.html
  soen341-frontend/src/styles.css
Labels: enhancement, Medium Priority, Medium Risk

#38 Login/Authentication-UI- #18
  soen341-backend/.idea/workspace.xml
  soen341-backend/src/main/java/soen341/backend/config/BeansConfig.java
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
  soen341-frontend/src/app/app.config.ts
  soen341-frontend/src/app/app.routes.ts
  soen341-frontend/src/app/home/home.component.html
  soen341-frontend/src/app/home/home.component.ts
  soen341-frontend/src/app/pages/activate-account/activate-account.component.css
  soen341-frontend/src/app/pages/activate-account/activate-account.component.html
  soen341-frontend/src/app/pages/activate-account/activate-account.component.spec.ts
  soen341-frontend/src/app/pages/activate-account/activate-account.component.ts
  soen341-frontend/src/app/pages/login/login.component.css
  soen341-frontend/src/app/pages/login/login.component.html
  soen341-frontend/src/app/pages/login/login.component.spec.ts
  soen341-frontend/src/app/pages/login/login.component.ts
  soen341-frontend/src/app/pages/register/register.component.css
  soen341-frontend/src/app/pages/register/register.component.html
  soen341-frontend/src/app/pages/register/register.component.spec.ts
  soen341-frontend/src/app/pages/register/register.component.ts
  soen341-frontend/src/app/services/api-configuration.ts
  soen341-frontend/src/app/services/api.module.ts
  soen341-frontend/src/app/services/base-service.ts
  soen341-frontend/src/app/services/fn/authentication/authenticate.ts
  soen341-frontend/src/app/services/fn/authentication/confirm.ts
  soen341-frontend/src/app/services/fn/authentication/register.ts
  soen341-frontend/src/app/services/models.ts
  soen341-frontend/src/app/services/models/authentication-request.ts
  soen341-frontend/src/app/services/models/authentication-response.ts
  soen341-frontend/src/app/services/models/registration-request.ts
  soen341-frontend/src/app/services/request-builder.ts
  soen341-frontend/src/app/services/services.ts
  soen341-frontend/src/app/services/services/authentication.service.ts
  soen341-frontend/src/app/services/strict-http-response.ts
  soen341-frontend/src/app/services/token/token.service.spec.ts
  soen341-frontend/src/app/services/token/token.service.ts
  soen341-frontend/src/openapi/openapi.json
Labels: High Priority, Blocking Priority, 13 pts, High Risk
