Repository ProjectSOEN341/Project_SOEN341, pull requests merged in 2025-03, with the labels that each got.

#61 Added unit test for account activation
  .github/workflows/main.yml
  .npmignore
  soen341-backend/.idea/workspace.xml
  soen341-frontend/package.json
  soen341-frontend/src/app/app.component.spec.ts
  soen341-frontend/src/app/home/home.component.spec.ts
  soen341-frontend/src/app/pages/activate-account/activate-account.component.spec.ts
  soen341-frontend/src/app/pages/activate-account/activate-account.component.ts
  soen341-frontend/src/app/pages/login/login.component.spec.ts
  soen341-frontend/src/app/pages/register/register.component.spec.ts
  soen341-frontend/src/app/pages/register/register.component.ts
Labels: 2 pts

#64 Task add unit tests for front end #59
  soen341-backend/.idea/workspace.xml
  soen341-frontend/src/app/app.routes.ts
  soen341-frontend/src/app/direct-messages/direct-messages.component.spec.ts
  soen341-frontend/src/app/home/home.component.spec.ts
  soen341-frontend/src/app/pages/login/login.component.spec.ts
  soen341-frontend/src/app/pages/register/register.component.spec.ts
  soen341-frontend/src/app/services/token/token.service.spec.ts
Labels: 3 pts

#66 New login UI
  soen341-backend/.idea/workspace.xml
  soen341-frontend/src/app/home/home.component.ts
  soen341-frontend/src/app/pages/activate-account/activate-account.component.css
  soen341-frontend/src/app/pages/activate-account/activate-account.component.html
  soen341-frontend/src/app/pages/activate-account/activate-account.component.ts
  soen341-frontend/src/app/pages/login/login.component.css
  soen341-frontend/src/app/pages/login/login.component.html
  soen341-frontend/src/app/pages/login/login.component.ts
  soen341-frontend/src/app/pages/register/register.component.css
  soen341-frontend/src/app/pages/register/register.component.html
  soen341-frontend/src/app/pages/register/register.component.ts
  soen341-frontend/src/index.html
Labels: Medium Priority, 2 pts, Medium Risk

#70 Error-messages-for-invalid-credentials-#67
  soen341-backend/.idea/workspace.xml
  soen341-backend/src/test/java/soen341/backend/TestcontainersConfiguration.java
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
  soen341-frontend/src/app/pages/login/login.component.css
  soen341-frontend/src/app/pages/login/login.component.html
  soen341-frontend/src/app/pages/login/login.component.spec.ts
  soen341-frontend/src/app/pages/login/login.component.ts
  soen341-frontend/src/app/pages/register/register.component.html
  soen341-frontend/src/app/pages/register/register.component.spec.ts
  soen341-frontend/src/app/pages/register/register.component.ts
  soen341-frontend/src/app/services/models.ts
Labels: Medium Priority, 3 pts, Medium Risk

#72 Update README.md
  README.md
Labels: documentation

#75 Task add google style formating tool GitHub action #74
  .github/workflows/main.yml
  soen341-backend/.idea/workspace.xml
  soen341-backend/src/main/java/soen341/backend/BackendApplication.java
  soen341-backend/src/main/java/soen341/backend/config/BeansConfig.java
  soen341-backend/src/main/java/soen341/backend/config/SecurityConfig.java
  soen341-backend/src/main/java/soen341/backend/config/WebSocketConfig.java
  soen341-backend/src/main/java/soen341/backend/controller/AuthenticationController.java
  soen341-backend/src/main/java/soen341/backend/controller/ChannelBrokerController.java
  soen341-backend/src/main/java/soen341/backend/controller/ChannelController.java
  soen341-backend/src/main/java/soen341/backend/controller/ChannelMessageController.java
  soen341-backend/src/main/java/soen341/backend/controller/ConversationController.java
  soen341-backend/src/main/java/soen341/backend/controller/MessageController.java
  soen341-backend/src/main/java/soen341/backend/controller/ParticipantController.java
  soen341-backend/src/main/java/soen341/backend/controller/UserController.java
  soen341-backend/src/main/java/soen341/backend/dto/ChannelDTO.java
  soen341-backend/src/main/java/soen341/backend/dto/ChannelMessageDTO.java
  soen341-backend/src/main/java/soen341/backend/dto/ConversationDTO.java
  soen341-backend/src/main/java/soen341/backend/dto/MessageDTO.java
  soen341-backend/src/main/java/soen341/backend/dto/UserDTO.java
  soen341-backend/src/main/java/soen341/backend/entity/Channel.java
  soen341-backend/src/main/java/soen341/backend/entity/ChannelMessage.java
  soen341-backend/src/main/java/soen341/backend/entity/Conversation.java
  soen341-backend/src/main/java/soen341/backend/entity/Message.java
  soen341-backend/src/main/java/soen341/backend/entity/Participant.java
  soen341-backend/src/main/java/soen341/backend/entity/Role.java
  soen341-backend/src/main/java/soen341/backend/entity/Token.java
  soen341-backend/src/main/java/soen341/backend/entity/User.java
  soen341-backend/src/main/java/soen341/backend/object/AuthenticationRequest.java
  soen341-backend/src/main/java/soen341/backend/object/AuthenticationResponse.java
  soen341-backend/src/main/java/soen341/backend/object/BusinessErrorCodes.java
  soen341-backend/src/main/java/soen341/backend/object/EmailTemplateName.java
  soen341-backend/src/main/java/soen341/backend/object/ExceptionResponse.java
  soen341-backend/src/main/java/soen341/backend/object/GlobalExceptionHandler.java
  soen341-backend/src/main/java/soen341/backend/object/RegistrationRequest.java
  soen341-backend/src/main/java/soen341/backend/repository/ChannelMessageRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/ChannelRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/ConversationRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/MessageRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/ParticipantRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/RoleRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/TokenRepository.java
  soen341-backend/src/main/java/soen341/backend/repository/UserRepository.java
  soen341-backend/src/main/java/soen341/backend/service/AuthenticationService.java
  soen341-backend/src/main/java/soen341/backend/service/ConversationService.java
  soen341-backend/src/main/java/soen341/backend/service/EmailService.java
  soen341-backend/src/main/java/soen341/backend/service/JwtFilterService.java
  soen341-backend/src/main/java/soen341/backend/service/JwtService.java
  soen341-backend/src/main/java/soen341/backend/service/UserDetailsServiceImpl.java
  soen341-backend/src/test/java/soen341/backend/BackendApplicationTests.java
  soen341-backend/src/test/java/soen341/backend/TestBackendApplication.java
  soen341-backend/src/test/java/soen341/backend/TestcontainersConfiguration.java
  soen341-frontend/angular.json
  soen341-frontend/eslint.config.js
  soen341-frontend/package-lock.json
  soen341-frontend/package.json
Labels: enhancement, High Priority, 1 pt, High Risk
